# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MeanHub Blog
tagline:             'MEAN stack technologies information hub'
description:         'MeanHub is a information hub for MEAN stack technologies MongoDB ExpressJS AngularJS NodeJS'
url:                 http://blog.meanhub.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              MeanHub
  url:               https://twitter.com/meanhubinc
  email:             info@meanhub.com
